Repository GDG-KU/GDG-KUDS-React, pull requests merged in 2024-12, with the labels that each got.

#13 Feat: Button 고도화
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/utils/classNames.ts
Labels: enhancement

#11 Feature: Inputs 컴포넌트
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/TextArea.stories.tsx
  src/components/Input/TextArea.tsx
Labels: feature

#14 Feat: Checkbox 컴포넌트 구현
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/index.ts
  src/components/index.ts
  src/icons/check.tsx
  src/utils/classNames.ts
Labels: feature

#10 storybook publish 스크립트 추가
  .github/workflows/gh-pages.yml
  .gitignore
  .storybook/preview-head.html
  package.json
  src/components/Label/Label.tsx
  yarn.lock
Labels: enhancement

#17 Docs: 업데이트 README.md
  .all-contributorsrc
  README.md
Labels: documentation

#18 Feat: Typogrpahy 리팩토링 및 스토리북 수정
  src/components/Typography/Header.stories.tsx
  src/components/Typography/Header.tsx
  src/components/Typography/Heading.tsx
  src/components/Typography/Typography.tsx
  src/components/Typography/Typoography.stories.tsx
  src/components/Typography/index.ts
Labels: enhancement
